/**
 * Node environment: `preloaded-years.ts` is pure functions over cards and a table, plus the
 * chunk's loader and its capped wait (fake timers).
 *
 * The second half checks the bundled JSON itself, because it is generated by a script and then
 * edited by hand -- the two ways a file drifts from the shape the app reads.
 */

import { afterEach, describe, expect, it, vi } from 'vitest';

import PRELOADED_YEARS from './preloaded-years.json';
import {
  PRELOADED_YEARS_MAX_WAIT_MS,
  PRELOADED_YEARS_OFF,
  applyPreloadedYears,
  isPreloadEnabled,
  loadPreloadedYears,
  preloadedYearsWithin,
  withPreloadedYears,
} from './preloaded-years';
import { gameReducer, initialGameState } from './reducer';
import { createYearResolver } from './resolver';
import { SUGGESTED_PLAYLISTS } from '../components/LandingScreen';
import type { ResolvedYear, ResolverLookup } from './resolver';
import type { YearLookupOutcome } from './year-client';
import type { Card } from '../../shared/types';

function card(id: string, overrides: Partial<Card> = {}): Card {
  return {
    id,
    title: `Title ${id}`,
    artist: `Artist ${id}`,
    durationMs: 200_000,
    isPlayable: true,
    ...overrides,
  };
}

const TABLE = {
  tracks: {
    high: { title: 'H', artist: 'A', year: 1984 },
    // A file from before every year counted as confirmed: the field is not read.
    legacyLow: { title: 'L', artist: 'A', year: 1999, confidence: 'low' },
    none: { title: 'N', artist: 'A', year: null },
    manual: { title: 'M', artist: 'A', year: 2013, note: 'Original single', providerYear: 2014 },
    stringYear: { title: 'X', artist: 'A', year: '1990' },
    fractionalYear: { title: 'X', artist: 'A', year: 1990.5 },
    missingYear: { title: 'X', artist: 'A' },
  },
};

describe('applyPreloadedYears', () => {
  it('should stamp a pending card with its year and confidence, and nothing else', () => {
    const [stamped] = applyPreloadedYears([card('high')], TABLE);

    expect(stamped).toEqual({ ...card('high'), year: 1984, yearConfidence: 'high' });
  });

  it('should stamp every year confirmed, ignoring a legacy confidence', () => {
    const [stamped] = applyPreloadedYears([card('legacyLow')], TABLE);

    expect(stamped).toEqual({ ...card('legacyLow'), year: 1999, yearConfidence: 'high' });
  });

  it('should stamp a final no-year as null at none', () => {
    const [stamped] = applyPreloadedYears([card('none')], TABLE);

    expect(stamped?.year).toBeNull();
    expect(stamped?.yearConfidence).toBe('none');
  });

  it('should never mark a stamped card provisional or unverified', () => {
    const stamped = applyPreloadedYears([card('legacyLow'), card('manual')], TABLE);

    for (const entry of stamped) {
      expect(entry.yearProvisional).toBeUndefined();
      expect(entry.yearVerifyAnswered).toBeUndefined();
      expect(entry.yearUnverified).toBeUndefined();
    }
  });

  it('should return a card the table does not know as the same object', () => {
    const unknown = card('unknown');

    expect(applyPreloadedYears([unknown], TABLE)[0]).toBe(unknown);
  });

  it('should leave a card that already holds an answer alone', () => {
    const resumed = card('high', { year: 1990, yearConfidence: 'low', yearProvisional: true });

    expect(applyPreloadedYears([resumed], TABLE)[0]).toBe(resumed);
  });

  it('should ignore an entry that is not a year a card may hold', () => {
    const cards = [card('stringYear'), card('fractionalYear'), card('missingYear')];

    expect(applyPreloadedYears(cards, TABLE)).toEqual(cards);
  });

  it('should not read inherited properties as entries', () => {
    const inherited = card('toString');

    expect(applyPreloadedYears([inherited], TABLE)[0]).toBe(inherited);
  });

  it('should deal a deck whose start card is preloaded without waiting, dropping preloaded nulls', () => {
    const state = gameReducer(initialGameState, {
      type: 'START',
      cards: applyPreloadedYears([card('high'), card('none')], TABLE),
      playlists: [{ id: 'p', name: 'P', owner: 'O' }],
      keepYearless: false,
      skipUnconfirmed: false,
    });

    expect(state.status).toBe('playing');
    expect(state.deck.map((entry) => entry.id)).toEqual(['high']);
  });

  it('should keep every preloaded year in a session that skips unconfirmed years', () => {
    const state = gameReducer(initialGameState, {
      type: 'START',
      cards: applyPreloadedYears([card('high'), card('legacyLow'), card('manual')], TABLE),
      playlists: [{ id: 'p', name: 'P', owner: 'O' }],
      keepYearless: false,
      skipUnconfirmed: true,
    });

    expect(state.status).toBe('playing');
    expect(state.deck.map((entry) => entry.id).sort()).toEqual(['high', 'legacyLow', 'manual']);
  });
});

describe('withPreloadedYears', () => {
  /** What the wrapped lookup answers for a track the table does not know: a network call. */
  const NETWORK: YearLookupOutcome = { ok: false, code: 'network' };

  function innerLookup() {
    return vi.fn<ResolverLookup>(() => Promise.resolve(NETWORK));
  }

  const signal = new AbortController().signal;

  it.each(['resolve', 'verify'] as const)(
    'should answer a known track final from the table at %s, sending no request',
    async (stage) => {
      const inner = innerLookup();
      const lookup = withPreloadedYears(inner, Promise.resolve(TABLE));

      const outcome = await lookup(card('legacyLow'), stage, signal);

      expect(inner).not.toHaveBeenCalled();
      expect(outcome).toMatchObject({
        ok: true,
        result: { year: 1999, confidence: 'high', final: true, cached: true },
      });
    },
  );

  it('should answer a known no-year as a final null at none', async () => {
    const lookup = withPreloadedYears(innerLookup(), Promise.resolve(TABLE));

    expect(await lookup(card('none'), 'resolve', signal)).toMatchObject({
      ok: true,
      result: { year: null, confidence: 'none', final: true },
    });
  });

  it('should pass an unknown track, an unusable entry and an inherited name to the lookup', async () => {
    for (const id of ['unknown', 'stringYear', 'fractionalYear', 'missingYear', 'toString']) {
      const inner = innerLookup();
      const lookup = withPreloadedYears(inner, Promise.resolve(TABLE));

      expect(await lookup(card(id), 'verify', signal), id).toBe(NETWORK);
      expect(inner, id).toHaveBeenCalledWith(card(id), 'verify', signal);
    }
  });

  it('should pass every track to the lookup when the table is off', async () => {
    const inner = innerLookup();
    const lookup = withPreloadedYears(inner, loadPreloadedYears(PRELOADED_YEARS_OFF));

    await lookup(card('high'), 'resolve', signal);

    expect(inner).toHaveBeenCalledOnce();
  });

  it('should settle a resumed pending and a resumed provisional card with no request', async () => {
    // The paths `applyPreloadedYears` never sees: a save or a Restart reaches the resolver with
    // a pending card the table knows, and with a provisional one owed a verify.
    const inner = innerLookup();
    const reports: ResolvedYear[] = [];
    let settle: () => void = () => undefined;
    const done = new Promise<void>((resolve) => {
      settle = resolve;
    });

    const resolver = createYearResolver(
      [card('high'), card('manual', { year: 2010, yearConfidence: 'low', yearProvisional: true })],
      {
        lookup: withPreloadedYears(inner, Promise.resolve(TABLE)),
        sleep: () => Promise.resolve(),
        onResolved: (resolved) => {
          reports.push(resolved);
          if (reports.length === 2) settle();
        },
        onLookupsUnavailable: () => undefined,
      },
    );
    resolver.start();
    await done;
    resolver.stop();

    expect(inner).not.toHaveBeenCalled();
    expect(reports).toEqual(
      expect.arrayContaining([
        { cardId: 'high', year: 1984, confidence: 'high' },
        { cardId: 'manual', year: 2013, confidence: 'high' },
      ]),
    );
  });
});

describe('isPreloadEnabled', () => {
  it('should be off only for the exact literal "off"', () => {
    expect(isPreloadEnabled(PRELOADED_YEARS_OFF)).toBe(false);
  });

  it.each([undefined, '', 'on', 'true', 'false', '0', 'OFF', ' off', 'of'])(
    'should stay on for %j, so a mistyped value never disables it',
    (flag) => {
      expect(isPreloadEnabled(flag)).toBe(true);
    },
  );
});

describe('loadPreloadedYears', () => {
  it('should resolve to the bundled tracks, and to the same promise on a second call', async () => {
    const first = loadPreloadedYears(undefined);

    expect(loadPreloadedYears(undefined)).toBe(first);
    expect((await first).tracks).toEqual(PRELOADED_YEARS.tracks);
  });

  it('should resolve to an empty table when the flag is off', async () => {
    expect((await loadPreloadedYears(PRELOADED_YEARS_OFF)).tracks).toEqual({});
  });
});

describe('preloadedYearsWithin', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  const LOADED = { tracks: { known: { year: 1984 } } };

  it('should resolve to the table when it settles inside the wait', async () => {
    vi.useFakeTimers();
    const waited = preloadedYearsWithin(Promise.resolve(LOADED), PRELOADED_YEARS_MAX_WAIT_MS);

    await expect(waited).resolves.toBe(LOADED);
    // The timer is cleared, so nothing is left to fire after a table that arrived in time.
    expect(vi.getTimerCount()).toBe(0);
  });

  it('should resolve to an empty table when the table is still loading at the limit', async () => {
    vi.useFakeTimers();
    const stalled = new Promise<typeof LOADED>(() => {});
    const waited = preloadedYearsWithin(stalled, PRELOADED_YEARS_MAX_WAIT_MS);

    await vi.advanceTimersByTimeAsync(PRELOADED_YEARS_MAX_WAIT_MS - 1);
    let settled = false;
    void waited.then(() => {
      settled = true;
    });
    await Promise.resolve();
    expect(settled).toBe(false);

    await vi.advanceTimersByTimeAsync(1);
    expect((await waited).tracks).toEqual({});
  });
});

describe('withPreloadedYears under a stalled table', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it('should wait for the table once, then fall through, and use it once it lands', async () => {
    vi.useFakeTimers();
    let land: (table: { tracks: Record<string, unknown> }) => void = () => {};
    const table = new Promise<{ tracks: Record<string, unknown> }>((resolve) => {
      land = resolve;
    });
    const inner = vi.fn<ResolverLookup>(() =>
      Promise.resolve({ ok: false, code: 'network' } as YearLookupOutcome),
    );
    const lookup = withPreloadedYears(inner, table);
    const signal = new AbortController().signal;

    // The first lookup waits out the deadline, then asks the network.
    const first = lookup(card('known'), 'resolve', signal);
    await vi.advanceTimersByTimeAsync(PRELOADED_YEARS_MAX_WAIT_MS);
    await first;
    expect(inner).toHaveBeenCalledTimes(1);

    // The next one does not wait again: no timer is advanced.
    await lookup(card('known'), 'resolve', signal);
    expect(inner).toHaveBeenCalledTimes(2);

    // A table that lands late answers every lookup after it.
    land({ tracks: { known: { title: 't', artist: 'a', year: 1984 } } });
    const late = await lookup(card('known'), 'resolve', signal);
    expect(inner).toHaveBeenCalledTimes(2);
    expect(late.ok && late.result.year).toBe(1984);
  });
});

describe('preloaded-years.json', () => {
  it('should cover exactly the suggested playlists', () => {
    expect(Object.keys(PRELOADED_YEARS.playlists).sort()).toEqual(
      SUGGESTED_PLAYLISTS.map((playlist) => playlist.id).sort(),
    );
  });

  it('should hold only answers a card may hold', () => {
    for (const id of Object.keys(PRELOADED_YEARS.tracks)) {
      const [stamped] = applyPreloadedYears([card(id)], PRELOADED_YEARS);

      expect(stamped?.year, id).not.toBeUndefined();
    }
  });

  it('should give every manual entry a provider year, and no entry a confidence or a source', () => {
    for (const [id, entry] of Object.entries(PRELOADED_YEARS.tracks)) {
      expect(entry, id).not.toHaveProperty('confidence');
      expect(entry, id).not.toHaveProperty('source');
      if (!('note' in entry)) continue;

      expect(typeof entry.note === 'string' && entry.note !== '', id).toBe(true);
      expect(entry, id).toHaveProperty('providerYear');
    }
  });
});
