/**
 * Node environment: `preloaded-years.ts` is a pure function over cards and a table.
 *
 * The second half checks the bundled JSON itself, because it is generated by a script and then
 * edited by hand -- the two ways a file drifts from the shape the app reads.
 */

import { describe, expect, it } from 'vitest';

import PRELOADED_YEARS from './preloaded-years.json';
import {
  PRELOADED_YEARS_OFF,
  applyPreloadedYears,
  isPreloadEnabled,
  loadPreloadedYears,
} from './preloaded-years';
import { gameReducer, initialGameState } from './reducer';
import { SUGGESTED_PLAYLISTS } from '../components/LandingScreen';
import type { Card } from '../../shared/types';

function card(id: string, overrides: Partial<Card> = {}): Card {
  return {
    id,
    title: `Title ${id}`,
    artist: `Artist ${id}`,
    durationMs: 200_000,
    isPlayable: true,
    ...overrides,
  };
}

const TABLE = {
  tracks: {
    high: { title: 'H', artist: 'A', year: 1984, confidence: 'high', source: 'providers' },
    low: { title: 'L', artist: 'A', year: 1999, confidence: 'low', source: 'providers' },
    none: { title: 'N', artist: 'A', year: null, confidence: 'none', source: 'providers' },
    manual: { title: 'M', artist: 'A', year: 2013, confidence: 'high', source: 'manual' },
    nullAtHigh: { title: 'X', artist: 'A', year: null, confidence: 'high', source: 'providers' },
    yearAtNone: { title: 'X', artist: 'A', year: 1990, confidence: 'none', source: 'providers' },
    stringYear: { title: 'X', artist: 'A', year: '1990', confidence: 'high', source: 'providers' },
  },
};

describe('applyPreloadedYears', () => {
  it('should stamp a pending card with its year and confidence, and nothing else', () => {
    const [stamped] = applyPreloadedYears([card('high')], TABLE);

    expect(stamped).toEqual({ ...card('high'), year: 1984, yearConfidence: 'high' });
  });

  it('should stamp a final no-year as null at none', () => {
    const [stamped] = applyPreloadedYears([card('none')], TABLE);

    expect(stamped?.year).toBeNull();
    expect(stamped?.yearConfidence).toBe('none');
  });

  it('should never mark a stamped card provisional or unverified', () => {
    const stamped = applyPreloadedYears([card('low'), card('manual')], TABLE);

    for (const entry of stamped) {
      expect(entry.yearProvisional).toBeUndefined();
      expect(entry.yearVerifyAnswered).toBeUndefined();
      expect(entry.yearUnverified).toBeUndefined();
    }
  });

  it('should return a card the table does not know as the same object', () => {
    const unknown = card('unknown');

    expect(applyPreloadedYears([unknown], TABLE)[0]).toBe(unknown);
  });

  it('should leave a card that already holds an answer alone', () => {
    const resumed = card('high', { year: 1990, yearConfidence: 'low', yearProvisional: true });

    expect(applyPreloadedYears([resumed], TABLE)[0]).toBe(resumed);
  });

  it('should ignore an entry that is not a year a card may hold', () => {
    const cards = [card('nullAtHigh'), card('yearAtNone'), card('stringYear')];

    expect(applyPreloadedYears(cards, TABLE)).toEqual(cards);
  });

  it('should not read inherited properties as entries', () => {
    const inherited = card('toString');

    expect(applyPreloadedYears([inherited], TABLE)[0]).toBe(inherited);
  });

  it('should deal a deck whose start card is preloaded without waiting, dropping preloaded nulls', () => {
    const state = gameReducer(initialGameState, {
      type: 'START',
      cards: applyPreloadedYears([card('high'), card('none')], TABLE),
      playlists: [{ id: 'p', name: 'P', owner: 'O' }],
      keepYearless: false,
      skipUnconfirmed: false,
    });

    expect(state.status).toBe('playing');
    expect(state.deck.map((entry) => entry.id)).toEqual(['high']);
  });
});

describe('isPreloadEnabled', () => {
  it('should be off only for the exact literal "off"', () => {
    expect(isPreloadEnabled(PRELOADED_YEARS_OFF)).toBe(false);
  });

  it.each([undefined, '', 'on', 'true', 'false', '0', 'OFF', ' off', 'of'])(
    'should stay on for %j, so a mistyped value never disables it',
    (flag) => {
      expect(isPreloadEnabled(flag)).toBe(true);
    },
  );
});

describe('loadPreloadedYears', () => {
  it('should resolve to the bundled tracks, and to the same promise on a second call', async () => {
    const first = loadPreloadedYears(undefined);

    expect(loadPreloadedYears(undefined)).toBe(first);
    expect((await first).tracks).toEqual(PRELOADED_YEARS.tracks);
  });

  it('should resolve to an empty table when the flag is off', async () => {
    expect((await loadPreloadedYears(PRELOADED_YEARS_OFF)).tracks).toEqual({});
  });
});

describe('preloaded-years.json', () => {
  it('should cover exactly the suggested playlists', () => {
    expect(Object.keys(PRELOADED_YEARS.playlists).sort()).toEqual(
      SUGGESTED_PLAYLISTS.map((playlist) => playlist.id).sort(),
    );
  });

  it('should hold only answers a card may hold', () => {
    for (const [id, entry] of Object.entries(PRELOADED_YEARS.tracks)) {
      const [stamped] = applyPreloadedYears([card(id)], PRELOADED_YEARS);

      expect(stamped?.year, id).not.toBeUndefined();
      expect(['providers', 'manual'], id).toContain(entry.source);
    }
  });

  it('should give every manual entry a note', () => {
    for (const [id, entry] of Object.entries(PRELOADED_YEARS.tracks)) {
      if (entry.source !== 'manual') continue;

      expect('note' in entry && typeof entry.note === 'string' && entry.note !== '', id).toBe(true);
    }
  });
});
