/**
 * Captured iTunes Search API responses for `api/_lib/itunes.test.ts` and the cross-layer
 * `api/_lib/year-votes.test.ts`: one capture per ground-truth track of
 * `shared/__fixtures__/year-candidates.ts` (the 21 `YEAR_FIXTURES` and Personal Jesus), keyed
 * by that file's `key`.
 *
 * RAW responses, trimmed; the answers they produce live in `shared/__fixtures__/year-votes.ts`
 * (see `deezer-payloads.ts` for why the two halves are split across `api/` and `shared/`).
 *
 * ## Provenance
 *
 * Captured 2026-09-30, 18:51-18:53 UTC, from `https://itunes.apple.com`, keyless, from one
 * machine in Spain, by a scratch script (`.scratch/plan2/capture.ts`, git-ignored) that
 * builds its URL exactly as the adapter does -- `itunesSearchUrl()` over
 * `primaryArtistGuess(artist)` and `cleanTrackTitle(title).title` -- with 3.2 s between
 * requests, under Apple's documented ~20 a minute. 22 requests, one per track, which is also
 * what the adapter spends. Never pointed at Upstash.
 *
 * ```
 * GET /search?term=<primary artist> <cleaned title>&entity=song&limit=10&country=ES
 * ```
 *
 * **Trimmed, not verbatim, and trimmed by FIELD only.** Every result row is kept, in Apple's
 * order, verified or not. Rows keep `wrapperType`, `kind`, `trackName`, `artistName`,
 * `trackTimeMillis` and `releaseDate` -- exactly what `itunes.ts` reads. Everything else was
 * dropped: the ids, `collectionName`, every URL and artwork link, the prices, the
 * explicitness flags, disc and track numbers, `country`, `currency`, `primaryGenreName`,
 * `isStreamable`, and the envelope's `resultCount`. Nothing was invented. The scratch
 * generator (`.scratch/plan2/gen.ts`) ran the adapter over the raw and the trimmed bodies and
 * got identical outcomes for all 22 tracks.
 *
 * ## Drift against the spike
 *
 * Checked against the spike's per-track answers for the 22 (spike §4.3, `fixtures-check.json`
 * in the spike session's scratchpad): **22 of 22 identical**, including Personal Jesus at
 * 1989 and the three nulls. The CSV holds none of the 22 (see `deezer-payloads.ts`); over a
 * seeded 30-track sample of it, captured live the same day, the adapter equals the CSV's
 * `itunes_year` 30 times of 30.
 *
 * The three nulls, all expected:
 *
 * - `noWomanNoCry`: the studio row is 226 s against the fixture's 255 s, outside
 *   `DURATION_TOLERANCE_MS`; the rows within 10 s are "(Remix)" titles, which the cleaner
 *   keeps, so the title rule rejects them.
 * - `creep`: Apple's ten rows are the acoustic take and covers; none is Radiohead's "Creep".
 * - `layla`: "Derek and the Dominos" against "Derek & The Dominos", the token "and" -- the
 *   same miss as Deezer's.
 *
 * No row here lacks `trackTimeMillis`, so the store-match rule that fails such a row (the
 * spike's harness passed it) changes nothing measured; the same was true of all 3 795 rows the
 * 542 recorded.
 */

/** One track's capture: the single search the adapter makes. */
export interface ItunesCapture {
  /** The `YEAR_FIXTURES` / `YEAR_LIMITATION_FIXTURES` key. */
  key: string;
  search: { url: string; body: unknown };
}

export const ITUNES_CAPTURES: readonly ItunesCapture[] = [
  {
    key: 'billieJean',
    search: {
      url: 'https://itunes.apple.com/search?term=Michael%20Jackson%20Billie%20Jean&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean (Single Version)',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294053,
            releaseDate: '1982-11-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean (Live)',
            artistName: 'Michael Jackson',
            trackTimeMillis: 338920,
            releaseDate: '2012-09-14T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean (Single Version)',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294601,
            releaseDate: '1982-11-30T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 293802,
            releaseDate: '1982-11-29T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean (Single Version)',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294601,
            releaseDate: '1982-11-30T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294188,
            releaseDate: '1982-11-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294188,
            releaseDate: '1982-11-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294188,
            releaseDate: '1982-11-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294237,
            releaseDate: '1982-11-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Billie Jean',
            artistName: 'Michael Jackson',
            trackTimeMillis: 294188,
            releaseDate: '1982-11-30T08:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'hotelCalifornia',
    search: {
      url: 'https://itunes.apple.com/search?term=Eagles%20Hotel%20California&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California (Remastered)',
            artistName: 'Eagles',
            trackTimeMillis: 391357,
            releaseDate: '1976-12-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California (Live On MTV, 1994)',
            artistName: 'Eagles',
            trackTimeMillis: 432040,
            releaseDate: '1994-11-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California (Live)',
            artistName: 'Eagles',
            trackTimeMillis: 420440,
            releaseDate: '1980-11-07T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California (Live at the Forum, Inglewood, CA, 2018)',
            artistName: 'Eagles',
            trackTimeMillis: 507373,
            releaseDate: '2020-10-16T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California (Live at the Los Angeles Forum, 10/20-22/76)',
            artistName: 'Eagles',
            trackTimeMillis: 409429,
            releaseDate: '1976-10-20T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California',
            artistName: 'Eagles',
            trackTimeMillis: 391357,
            releaseDate: '1976-12-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California',
            artistName: 'Eagles',
            trackTimeMillis: 391376,
            releaseDate: '1976-12-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California',
            artistName: 'Eagles',
            trackTimeMillis: 391357,
            releaseDate: '1976-12-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California',
            artistName: 'Eagles',
            trackTimeMillis: 391357,
            releaseDate: '1976-12-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hotel California',
            artistName: 'Eagles',
            trackTimeMillis: 391357,
            releaseDate: '1976-12-08T08:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'sweetChild',
    search: {
      url: "https://itunes.apple.com/search?term=Guns%20N'%20Roses%20Sweet%20Child%20O'%20Mine&entity=song&limit=10&country=ES",
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine",
            artistName: "Guns N' Roses",
            trackTimeMillis: 356067,
            releaseDate: '1987-07-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine",
            artistName: "Guns N' Roses",
            trackTimeMillis: 356067,
            releaseDate: '1987-07-21T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine (Live)",
            artistName: "Guns N' Roses",
            trackTimeMillis: 445200,
            releaseDate: '1999-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine (Live In New York, Ritz Theatre - May 16, 1991)",
            artistName: "Guns N' Roses",
            trackTimeMillis: 469099,
            releaseDate: '1991-09-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              "Sweet Child O' Mine (Live In Las Vegas, Thomas & Mack Center - January 25, 1992)",
            artistName: "Guns N' Roses",
            trackTimeMillis: 442211,
            releaseDate: '1991-09-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine",
            artistName: "Guns N' Roses",
            trackTimeMillis: 355267,
            releaseDate: '1987-07-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine (Live)",
            artistName: "Guns N' Roses",
            trackTimeMillis: 445173,
            releaseDate: '1999-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine (feat. Myles Kennedy) [Live]",
            artistName: 'Slash',
            trackTimeMillis: 388853,
            releaseDate: '2011-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine",
            artistName: 'Rockabye Baby!',
            trackTimeMillis: 187907,
            releaseDate: '2009-11-10T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Sweet Child O' Mine",
            artistName: 'Renee & Jeremy, Renee Stahl & Jeremy Toback',
            trackTimeMillis: 200047,
            releaseDate: '2021-05-14T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'noWomanNoCry',
    search: {
      url: 'https://itunes.apple.com/search?term=Bob%20Marley%20%26%20The%20Wailers%20No%20Woman%20No%20Cry&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live At The Lyceum, London/1975)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 429557,
            releaseDate: '1984-05-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Remix)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 251240,
            releaseDate: '1997-09-23T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live 1975)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 429200,
            releaseDate: '1984-05-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Remixed)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 251067,
            releaseDate: '1980-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 226061,
            releaseDate: '1974-10-25T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live 1975)',
            artistName: 'Bob Marley',
            trackTimeMillis: 425268,
            releaseDate: '1975-12-05T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              'No Woman, No Cry (Live At The Rainbow Theatre, London / 4th June 1977 / Remastered 2020)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 421418,
            releaseDate: '2020-06-12T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live at The Lyceum, London, 1975)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 431213,
            releaseDate: '1975-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live at The Lyceum, London July 18, 1975)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 426651,
            releaseDate: '1975-12-05T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'No Woman, No Cry (Live at Ahoy Hallen, 1978)',
            artistName: 'Bob Marley & The Wailers',
            trackTimeMillis: 402360,
            releaseDate: '2013-04-19T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'wishYouWereHere',
    search: {
      url: 'https://itunes.apple.com/search?term=Pink%20Floyd%20Wish%20You%20Were%20Here&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here',
            artistName: 'Pink Floyd',
            trackTimeMillis: 338467,
            releaseDate: '1975-09-12T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here (Take 1)',
            artistName: 'Pink Floyd',
            trackTimeMillis: 300520,
            releaseDate: '2025-11-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here (Live)',
            artistName: 'Pink Floyd',
            trackTimeMillis: 395920,
            releaseDate: '1995-05-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here (Live)',
            artistName: 'Pink Floyd',
            trackTimeMillis: 289093,
            releaseDate: '1988-11-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here (2019 Remix) [Live]',
            artistName: 'Pink Floyd',
            trackTimeMillis: 278493,
            releaseDate: '1988-11-22T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here',
            artistName: 'Pink Floyd',
            trackTimeMillis: 304200,
            releaseDate: '1975-09-12T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here',
            artistName: 'Pink Floyd',
            trackTimeMillis: 338267,
            releaseDate: '1975-09-12T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here',
            artistName: 'Pink Floyd',
            trackTimeMillis: 321080,
            releaseDate: '1975-09-12T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here',
            artistName: 'Pink Floyd',
            trackTimeMillis: 324893,
            releaseDate: '1975-09-12T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Wish You Were Here (Live)',
            artistName: 'The Australian Pink Floyd Show',
            trackTimeMillis: 345960,
            releaseDate: '2012-09-24T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'stairwayToHeaven',
    search: {
      url: 'https://itunes.apple.com/search?term=Led%20Zeppelin%20Stairway%20to%20Heaven&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 482830,
            releaseDate: '1971-11-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 482830,
            releaseDate: '1971-11-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (Live)',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 577013,
            releaseDate: '2003-05-27T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (1/4/71 Paris Theatre)',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 529373,
            releaseDate: '1997-11-11T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 485013,
            releaseDate: '1971-11-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (Live)',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 653027,
            releaseDate: '1976-09-28T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 482830,
            releaseDate: '1971-11-08T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (Live)',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 529527,
            releaseDate: '2012-11-16T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (Sunset Sound Mix)',
            artistName: 'Led Zeppelin',
            trackTimeMillis: 483667,
            releaseDate: '2014-10-27T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Stairway to Heaven (Live)',
            artistName: 'LA Thunder',
            trackTimeMillis: 654764,
            releaseDate: '2007-02-28T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'bohemianRhapsody',
    search: {
      url: 'https://itunes.apple.com/search?term=Queen%20Bohemian%20Rhapsody&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody',
            artistName: 'Queen',
            trackTimeMillis: 354947,
            releaseDate: '1975-10-31T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody (Live Aid)',
            artistName: 'Queen',
            trackTimeMillis: 147840,
            releaseDate: '2018-10-19T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody',
            artistName: 'Queen',
            trackTimeMillis: 355155,
            releaseDate: '1975-10-31T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody',
            artistName: 'Queen',
            trackTimeMillis: 355145,
            releaseDate: '1975-10-31T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody',
            artistName: 'Queen',
            trackTimeMillis: 355155,
            releaseDate: '1975-10-31T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody',
            artistName: 'Queen',
            trackTimeMillis: 355467,
            releaseDate: '1975-10-31T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody (Operatic Section / 2011 A Cappella Mix)',
            artistName: 'Queen',
            trackTimeMillis: 64969,
            releaseDate: '1975-11-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody (Live)',
            artistName: 'Queen',
            trackTimeMillis: 328933,
            releaseDate: '2007-10-29T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody (Live At Wembley Stadium / July 1986)',
            artistName: 'Queen',
            trackTimeMillis: 350613,
            releaseDate: '1990-12-10T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Bohemian Rhapsody (Live, European Tour / 1979)',
            artistName: 'Queen',
            trackTimeMillis: 352040,
            releaseDate: '1979-06-22T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'hallelujahBuckley',
    search: {
      url: 'https://itunes.apple.com/search?term=Jeff%20Buckley%20Hallelujah&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 413827,
            releaseDate: '1994-08-23T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Live at Bearsville Studios, New York - 1993)',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 395172,
            releaseDate: '2007-05-18T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 429709,
            releaseDate: '2019-03-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Radio Edit)',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 255723,
            releaseDate: '2007-05-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 413320,
            releaseDate: '1994-08-23T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Radio Edit)',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 255400,
            releaseDate: '2007-05-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Radio Edit)',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 256920,
            releaseDate: '2007-05-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 412440,
            releaseDate: '1994-08-23T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Radio Edit)',
            artistName: 'Jeff Buckley',
            trackTimeMillis: 255440,
            releaseDate: '2007-05-22T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'hallelujahCohen',
    search: {
      url: 'https://itunes.apple.com/search?term=Leonard%20Cohen%20Hallelujah&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Leonard Cohen',
            trackTimeMillis: 278573,
            releaseDate: '1984-12-01T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Leonard Cohen',
            trackTimeMillis: 279902,
            releaseDate: '1984-12-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Live)',
            artistName: 'Leonard Cohen',
            trackTimeMillis: 440093,
            releaseDate: '2009-03-31T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Leonard Cohen',
            trackTimeMillis: 414640,
            releaseDate: '1975-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Aleluya)',
            artistName: 'Il Divo',
            trackTimeMillis: 199573,
            releaseDate: '2008-11-18T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah (Aleluya)',
            artistName: 'Il Divo',
            trackTimeMillis: 199853,
            releaseDate: '2008-11-18T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'Andrea Bocelli',
            trackTimeMillis: 274347,
            releaseDate: '2020-11-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Leonard Cohen: Hallelujah',
            artistName: 'Trio Fibonacci',
            trackTimeMillis: 314214,
            releaseDate: '2023-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: '2CELLOS',
            trackTimeMillis: 217427,
            releaseDate: '2018-10-19T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hallelujah',
            artistName: 'André Rieu & Johann Strauss Orchestra',
            trackTimeMillis: 205000,
            releaseDate: '2016-10-14T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'freeBird',
    search: {
      url: 'https://itunes.apple.com/search?term=Lynyrd%20Skynyrd%20Free%20Bird&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 552751,
            releaseDate: '1973-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (TOTEM Remix)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 166500,
            releaseDate: '2022-12-02T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Demo Version)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 247093,
            releaseDate: '1973-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Undubbed) [Live]',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 865867,
            releaseDate: '1976-09-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Extended Music Version)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 607373,
            releaseDate: '1973-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 549640,
            releaseDate: '1973-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Live At Reunion Arena, Dallas/1987)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 891333,
            releaseDate: '1988-03-21T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Live at the Fox Theater/1976)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 863120,
            releaseDate: '2000-03-14T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 550067,
            releaseDate: '1973-08-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Free Bird (Live At The Fox Theater, 1976)',
            artistName: 'Lynyrd Skynyrd',
            trackTimeMillis: 821067,
            releaseDate: '1976-09-01T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'likeARollingStone',
    search: {
      url: 'https://itunes.apple.com/search?term=Bob%20Dylan%20Like%20a%20Rolling%20Stone&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 371714,
            releaseDate: '1965-07-20T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone (Live at LA Forum, Inglewood, CA - February 1974)',
            artistName: 'Bob Dylan & The Band',
            trackTimeMillis: 429116,
            releaseDate: '1974-06-20T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 319040,
            releaseDate: '1970-06-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              'Like a Rolling Stone (Live at Nippon Budokan Hall, Tokyo, Japan - February/March 1978)',
            artistName: 'Bob Dylan',
            trackTimeMillis: 397133,
            releaseDate: '1979-04-23T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              'Like a Rolling Stone (Live at Sony Music Studios, New York, NY - November 1994)',
            artistName: 'Bob Dylan',
            trackTimeMillis: 549760,
            releaseDate: '1995-04-25T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 368467,
            releaseDate: '1965-07-20T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 368187,
            releaseDate: '1965-07-20T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 367507,
            releaseDate: '1965-07-20T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone (Live)',
            artistName: 'Bob Dylan',
            trackTimeMillis: 492480,
            releaseDate: '2005-08-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Like a Rolling Stone',
            artistName: 'Bob Dylan',
            trackTimeMillis: 367381,
            releaseDate: '1965-07-20T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'layla',
    search: {
      url: 'https://itunes.apple.com/search?term=Derek%20and%20the%20Dominos%20Layla&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla',
            artistName: 'Derek & The Dominos',
            trackTimeMillis: 423840,
            releaseDate: '1970-11-09T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla (40th Anniversary Version)',
            artistName: 'Derek & The Dominos',
            trackTimeMillis: 429093,
            releaseDate: '2018-06-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla',
            artistName: 'Derek & The Dominos & Eric Clapton',
            trackTimeMillis: 430667,
            releaseDate: '1970-11-09T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla',
            artistName: 'Derek & The Dominos',
            trackTimeMillis: 423840,
            releaseDate: '1970-11-09T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla',
            artistName: 'Eric Clapton & Derek & The Dominos',
            trackTimeMillis: 423013,
            releaseDate: '1970-11-09T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla (Alternate Mix)',
            artistName: 'Derek & The Dominos',
            trackTimeMillis: 427674,
            releaseDate: '1972-11-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla (Acoustic Live)',
            artistName: 'Eric Clapton',
            trackTimeMillis: 289027,
            releaseDate: '1992-08-25T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla (Live)',
            artistName: 'Eric Clapton',
            trackTimeMillis: 260440,
            releaseDate: '1992-08-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla',
            artistName: 'Eric Clapton',
            trackTimeMillis: 338440,
            releaseDate: '1996-04-02T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Layla (Acoustic Live)',
            artistName: 'Eric Clapton',
            trackTimeMillis: 289027,
            releaseDate: '1992-08-25T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'allAlongTheWatchtower',
    search: {
      url: 'https://itunes.apple.com/search?term=Jimi%20Hendrix%20All%20Along%20the%20Watchtower&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'Jimi Hendrix',
            trackTimeMillis: 241138,
            releaseDate: '1968-09-21T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower (Live)',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 259533,
            releaseDate: '2015-08-28T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'Jimi Hendrix',
            trackTimeMillis: 241240,
            releaseDate: '1968-09-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 240800,
            releaseDate: '1968-09-16T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 239760,
            releaseDate: '1968-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 240800,
            releaseDate: '1968-09-16T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower (Live)',
            artistName: 'Jimi Hendrix',
            trackTimeMillis: 340262,
            releaseDate: '2002-11-12T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 238627,
            releaseDate: '1993-09-28T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'All Along the Watchtower',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 238627,
            releaseDate: '1968-09-21T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              'All Along the Watchtower (Live at the Isle of Wight, England, UK, August 30, 1970)',
            artistName: 'The Jimi Hendrix Experience',
            trackTimeMillis: 262720,
            releaseDate: '2000-09-11T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'smellsLikeTeenSpirit',
    search: {
      url: 'https://itunes.apple.com/search?term=Nirvana%20Smells%20Like%20Teen%20Spirit&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName:
              'Smells Like Teen Spirit (Live At Del Mar Fairgrounds, CA., December 28, 1991)',
            artistName: 'Nirvana',
            trackTimeMillis: 287067,
            releaseDate: '1996-10-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit (Remastered)',
            artistName: 'Nirvana',
            trackTimeMillis: 300893,
            releaseDate: '1991-09-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit',
            artistName: 'Nirvana',
            trackTimeMillis: 301096,
            releaseDate: '1991-09-10T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit (Devonshire Mix)',
            artistName: 'Nirvana',
            trackTimeMillis: 302040,
            releaseDate: '1991-09-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit',
            artistName: 'Nirvana',
            trackTimeMillis: 301096,
            releaseDate: '1991-09-10T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit (Live At the Paramount)',
            artistName: 'Nirvana',
            trackTimeMillis: 285573,
            releaseDate: '1991-09-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit',
            artistName: 'Nirvana',
            trackTimeMillis: 301453,
            releaseDate: '1991-09-10T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit (Boombox Rehearsals)',
            artistName: 'Nirvana',
            trackTimeMillis: 340480,
            releaseDate: '1991-09-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit',
            artistName: 'Malia J',
            trackTimeMillis: 239000,
            releaseDate: '2021-07-02T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Smells Like Teen Spirit',
            artistName: 'Robyn Adele Anderson',
            trackTimeMillis: 220056,
            releaseDate: '2019-02-26T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'creep',
    search: {
      url: 'https://itunes.apple.com/search?term=Radiohead%20Creep&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep (Acoustic)',
            artistName: 'Radiohead',
            trackTimeMillis: 258640,
            releaseDate: '1992-09-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep (feat. Radiohead) [Very 2021 Rmx]',
            artistName: 'Thom Yorke',
            trackTimeMillis: 542732,
            releaseDate: '2021-07-13T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Daniela Andrade',
            trackTimeMillis: 214000,
            releaseDate: '2013-04-04T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep (feat. Haley Reinhart)',
            artistName: "Scott Bradlee's Postmodern Jukebox & Postmodern Jukebox",
            trackTimeMillis: 283259,
            releaseDate: '2015-04-07T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'TLC',
            trackTimeMillis: 268533,
            releaseDate: '1994-10-31T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Arlo Parks',
            trackTimeMillis: 277895,
            releaseDate: '2020-06-11T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Karen Souza',
            trackTimeMillis: 211307,
            releaseDate: '2005-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Elin Porsinger',
            trackTimeMillis: 204328,
            releaseDate: '2021-08-06T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Kina Grannis',
            trackTimeMillis: 234135,
            releaseDate: '2017-04-14T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Creep',
            artistName: 'Karen Souza',
            trackTimeMillis: 207601,
            releaseDate: '2005-01-01T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'relax',
    search: {
      url: 'https://itunes.apple.com/search?term=Frankie%20Goes%20to%20Hollywood%20Relax&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax (New York Mix)',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 443234,
            releaseDate: '1983-10-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax (New York Mix)',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 444560,
            releaseDate: '1984-06-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 233613,
            releaseDate: '1983-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 237933,
            releaseDate: '1983-10-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax (New York Mix)',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 444507,
            releaseDate: '2006-09-19T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax (Rough Mix / Sunday 4th September 1983)',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 248000,
            releaseDate: '1984-10-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Relax (Lockout's Radio Edit)",
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 212347,
            releaseDate: '1993-09-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 236800,
            releaseDate: '1983-10-24T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 237493,
            releaseDate: '1983-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Relax (Come Fighting)',
            artistName: 'Frankie Goes to Hollywood',
            trackTimeMillis: 236787,
            releaseDate: '1983-10-24T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'underPressure',
    search: {
      url: 'https://itunes.apple.com/search?term=Queen%20%26%20David%20Bowie%20Under%20Pressure&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie)',
            artistName: 'Queen',
            trackTimeMillis: 248440,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie) [Rah Mix]',
            artistName: 'Queen',
            trackTimeMillis: 249453,
            releaseDate: '1999-11-08T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie)',
            artistName: 'Queen',
            trackTimeMillis: 236507,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie)',
            artistName: 'Queen',
            trackTimeMillis: 244485,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie)',
            artistName: 'Queen',
            trackTimeMillis: 236512,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (feat. David Bowie)',
            artistName: 'Queen',
            trackTimeMillis: 248440,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure',
            artistName: 'Queen & David Bowie',
            trackTimeMillis: 244747,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (Single Version) [2017 Remastered Version]',
            artistName: 'Queen & David Bowie',
            trackTimeMillis: 248720,
            releaseDate: '2017-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure (2011 Remastered Version)',
            artistName: 'Queen & David Bowie',
            trackTimeMillis: 244747,
            releaseDate: '1981-10-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Under Pressure',
            artistName: 'Queen & David Bowie',
            trackTimeMillis: 237520,
            releaseDate: '1981-10-26T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'firestarter',
    search: {
      url: 'https://itunes.apple.com/search?term=The%20Prodigy%20Firestarter&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter',
            artistName: 'The Prodigy',
            trackTimeMillis: 279800,
            releaseDate: '1996-03-18T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Edit)',
            artistName: 'The Prodigy',
            trackTimeMillis: 227427,
            releaseDate: '1996-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter',
            artistName: 'The Prodigy',
            trackTimeMillis: 279800,
            releaseDate: '1996-03-18T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter',
            artistName: 'The Prodigy',
            trackTimeMillis: 279800,
            releaseDate: '1996-03-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Alvin Risk Remix)',
            artistName: 'The Prodigy',
            trackTimeMillis: 198333,
            releaseDate: '2012-12-03T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Empirion Mix)',
            artistName: 'The Prodigy',
            trackTimeMillis: 471733,
            releaseDate: '1996-03-15T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter',
            artistName: 'The Prodigy',
            trackTimeMillis: 279800,
            releaseDate: '1996-03-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Live)',
            artistName: 'The Prodigy',
            trackTimeMillis: 321280,
            releaseDate: '2005-10-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Andy C Remix)',
            artistName: 'The Prodigy & Andy C',
            trackTimeMillis: 232500,
            releaseDate: '2022-06-30T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Firestarter (Andy C Remix)',
            artistName: 'The Prodigy & Andy C',
            trackTimeMillis: 232500,
            releaseDate: '2022-06-30T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'mrBrightside',
    search: {
      url: 'https://itunes.apple.com/search?term=The%20Killers%20Mr.%20Brightside&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside',
            artistName: 'The Killers',
            trackTimeMillis: 222973,
            releaseDate: '2003-09-29T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside',
            artistName: 'The Killers',
            trackTimeMillis: 222200,
            releaseDate: '2003-09-23T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside (Live at Connect / 2004)',
            artistName: 'The Killers',
            trackTimeMillis: 223867,
            releaseDate: '2004-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside',
            artistName: 'The Killers',
            trackTimeMillis: 223027,
            releaseDate: '2003-09-29T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside',
            artistName: 'The Killers',
            trackTimeMillis: 223973,
            releaseDate: '2003-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside (Original Demo)',
            artistName: 'The Killers',
            trackTimeMillis: 262560,
            releaseDate: '2003-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Mr. Brightside (Jacques Lu Cont's Thin White Duke Mix)",
            artistName: 'The Killers',
            trackTimeMillis: 528553,
            releaseDate: '2003-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: "Mr. Brightside (Jacques Lu Cont's Thin White Duke Mix)",
            artistName: 'The Killers',
            trackTimeMillis: 530080,
            releaseDate: '2003-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside',
            artistName: 'The Killers',
            trackTimeMillis: 223973,
            releaseDate: '2003-09-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Mr. Brightside (Live from The Royal Albert Hall / 2009)',
            artistName: 'The Killers',
            trackTimeMillis: 233440,
            releaseDate: '2009-11-03T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'rollingInTheDeep',
    search: {
      url: 'https://itunes.apple.com/search?term=Adele%20Rolling%20in%20the%20Deep&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep',
            artistName: 'Adele',
            trackTimeMillis: 228093,
            releaseDate: '2010-11-29T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep (Acapella)',
            artistName: 'Adele',
            trackTimeMillis: 236778,
            releaseDate: '2011-01-16T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling in the Deep (Live)',
            artistName: 'Adele',
            trackTimeMillis: 321084,
            releaseDate: '2011-07-13T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep (Live)',
            artistName: 'LINKIN PARK',
            trackTimeMillis: 264864,
            releaseDate: '2011-07-07T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep',
            artistName: 'Adele',
            trackTimeMillis: 228093,
            releaseDate: '2010-11-29T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep (Jamie xx Shuffle)',
            artistName: 'Adele',
            trackTimeMillis: 257652,
            releaseDate: '2011-01-16T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling in the Deep',
            artistName: 'Bossa Nova Covers & Mats & My',
            trackTimeMillis: 223889,
            releaseDate: '2022-01-21T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling in the Deep',
            artistName: 'Shirley Adamson',
            trackTimeMillis: 246602,
            releaseDate: '2017-05-12T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling In the Deep (The Aretha Version)',
            artistName: 'Aretha Franklin',
            trackTimeMillis: 240305,
            releaseDate: '2014-09-29T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Rolling in the Deep (feat. Monique)',
            artistName: 'Urban Love',
            trackTimeMillis: 248147,
            releaseDate: '2006-01-01T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'heyJude',
    search: {
      url: 'https://itunes.apple.com/search?term=The%20Beatles%20Hey%20Jude&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'The Beatles',
            trackTimeMillis: 431333,
            releaseDate: '1968-08-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'The Beatles',
            trackTimeMillis: 429933,
            releaseDate: '1968-08-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'The Beatles',
            trackTimeMillis: 425653,
            releaseDate: '1968-08-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude (Take 1)',
            artistName: 'The Beatles',
            trackTimeMillis: 404480,
            releaseDate: '1968-11-22T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'The Beatles',
            trackTimeMillis: 432200,
            releaseDate: '1968-08-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'The Beatles',
            trackTimeMillis: 238854,
            releaseDate: '2006-11-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude (2015 Mix)',
            artistName: 'The Beatles',
            trackTimeMillis: 431453,
            releaseDate: '1968-08-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude (Live)',
            artistName: 'Paul McCartney',
            trackTimeMillis: 483427,
            releaseDate: '1990-01-01T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude (Live at CitiField, NYC)',
            artistName: 'Paul McCartney',
            trackTimeMillis: 442747,
            releaseDate: '2009-11-17T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Hey Jude',
            artistName: 'Rockabye Baby!',
            trackTimeMillis: 273400,
            releaseDate: '2007-03-13T12:00:00Z',
          },
        ],
      },
    },
  },
  {
    key: 'personalJesus',
    search: {
      url: 'https://itunes.apple.com/search?term=Depeche%20Mode%20Personal%20Jesus&entity=song&limit=10&country=ES',
      body: {
        results: [
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus',
            artistName: 'Depeche Mode',
            trackTimeMillis: 295960,
            releaseDate: '1989-08-28T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (Single Version)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 224933,
            releaseDate: '1987-08-29T07:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (LiVE SPiRiTS)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 377160,
            releaseDate: '2020-06-26T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (Boys Noize Rework)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 415467,
            releaseDate: '2006-11-07T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus',
            artistName: 'Depeche Mode',
            trackTimeMillis: 224147,
            releaseDate: '1989-08-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (The Stargate Mix)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 238507,
            releaseDate: '2011-04-19T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus',
            artistName: 'Depeche Mode',
            trackTimeMillis: 225040,
            releaseDate: '1987-08-29T12:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus',
            artistName: 'Depeche Mode',
            trackTimeMillis: 295960,
            releaseDate: '1990-03-19T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (Live at the O2 World, Berlin, November 2013)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 522187,
            releaseDate: '2014-11-14T08:00:00Z',
          },
          {
            wrapperType: 'track',
            kind: 'song',
            trackName: 'Personal Jesus (Eric Prydz Remix)',
            artistName: 'Depeche Mode',
            trackTimeMillis: 444240,
            releaseDate: '2011-05-30T12:00:00Z',
          },
        ],
      },
    },
  },
];
